spring:
  application:
    name: loicpay-service
  datasource:
    url: jdbc:sqlite:/Users/botlp/Temp/loicpay-batch.db  # Remplace avec le chemin correct vers ta DB
    driverClassName: org.sqlite.JDBC
    username: ""
    password: ""
  jdbc:
    # Utilisation d'HikariCP pour la gestion des connexions
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none  # Pas de gestion automatique des tables (en l'absence de JPA)
