export enum UploadFileType {
    LOIC_PAYMENT = 'LOIC_PAYMENT',
    LOIC_RECOVERY = 'LOIC_RECOVERY',
    LOIC_ERROR = 'LOIC_ERROR',
    MFX_PAYMENT = 'MFX_PAYMENT',
    MFX_RECOVERY = 'MFX_RECOVERY',
}
